### ISSUE TITLE
support opening a file from the integrated terminal command line

### ISSUE THREAD

**Issue by alexjwilliams** [leep-frog/termin-all-or-nothing#1]
It would be great if you could add support for what is stated in the title of this issue. For example, running `code myfile.txt` from the integrated terminal command line should cause the terminal to be hidden completely. Currently (v2.2.1), when `code myfile.txt` is executed from a terminal that is completely maximized, the terminal moves down the screen just a little to reveal myfile.txt.

**Comment by leep-frog** [comment]
Strange, when running `code NAME.txt` myself, it sometimes auto-closes for me and sometimes doesn't 🤷 .  It seems like the main hook I'm using (`onDidChangeTextEditorVisibleRanges`) only occasionally gets triggered when opening files through `code NAME.txt` (no clue why though). I added another hook for `onDidChangeVisibleTextEditors` to try and catch this extra case and it seems to work well enough. I just finished putting it together fully in 3.0.5.  Give that a try and let me know if that works and/or if you see any other issues with that version.

I'll leave it to you to close the issue or continue the thread

**Comment by alexjwilliams** [comment]
I had to stop using the plugin due to [this issue](https://github.com/leep-frog/termin-all-or-nothing/blob/main/docs/FAQ.md#output-tab-closes-immediately-after-opening-solutions-provided). I'm sorry if I wasted your time.

**Comment by leep-frog** [comment]
Not a waste of time at all!  Quite the contrary actually--I didn't realize this extension was even being used by people so I'm glad you pulled me back in!

Also, I was able to mess around with this some more today and actually found another implementation approach (see version 4.0.1) that fixes most of the old issues (including all of the ones in the previous `Known Issues` page like the one you encountered). It's been working well for me throughout the day today with no big hiccups and I'd definitely appreciate it if you gave it another try (as well as any additional feedback you have with the new version).

Feel free to re-resolve after retrying if you're up for giving it another go

**Comment by leep-frog** [comment]
@alexjwilliams any chance you're able to try this out again?  I'd appreciate the feedback on the new revision, but understandable if not

**Comment by alexjwilliams** [comment]
Thank you for the changes, but I am still not using the plugin. Sorry. My configuration is evolving and I may pick up this plugin again in the future.

**Comment by leep-frog** [comment]
Ah, sorry to hear.  Happy to get any feedback if you decide to use it again though.
